com.fasterxml.jackson.*:* = 2.21.4
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.netflix.nebula:nebula-test = 10.6.2
io.github.gradle-nexus:publish-plugin = 2.0.0
com.netflix.nebula:nebula-publishing-plugin = 23.1.0
com.netflix.nebula:gradle-info-plugin = 16.3.0
org.junit.platform:* = 6.1.0
org.rauschig:jarchivelib = 1.2.0
com.google.guava:guava = 33.6.0-jre
com.palantir.gradle.gitversion:gradle-git-version = 5.0.0
com.palantir.gradle.utils:environment-variables = 0.24.0
com.palantir.safe-logging:preconditions = 3.16.0
org.jetbrains.intellij.plugins:gradle-intellij-plugin = 1.17.3
org.immutables:* = 2.12.2
org.junit.jupiter:* = 6.1.0
com.gradle.publish:plugin-publish-plugin = 2.0.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.47.0
org.checkerframework:checker-qual = 4.2.0
