com.fasterxml.jackson.*:* = 2.20.1
com.fasterxml.jackson.core:jackson-annotations = 2.20
com.netflix.nebula:nebula-test = 10.6.2
io.github.gradle-nexus:publish-plugin = 2.0.0
com.netflix.nebula:nebula-publishing-plugin = 23.0.0
com.netflix.nebula:gradle-info-plugin = 16.0.1
org.junit.platform:* = 6.0.2
org.rauschig:jarchivelib = 1.1.0
com.google.guava:guava = 33.5.0-jre
com.palantir.gradle.gitversion:gradle-git-version = 4.3.0
com.palantir.gradle.utils:environment-variables = 0.21.0
com.palantir.safe-logging:preconditions = 3.11.0
org.jetbrains.intellij.plugins:gradle-intellij-plugin = 1.17.3
org.immutables:* = 2.12.1
org.junit.jupiter:* = 6.0.2
com.gradle.publish:plugin-publish-plugin = 2.0.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
org.checkerframework:checker-qual = 3.53.0
