apply plugin: 'java-library'
apply plugin: 'com.palantir.external-publish-jar'

dependencies {
    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'

    api gradleApi()
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.google.guava:guava'
    implementation 'com.palantir.gradle.gitversion:gradle-git-version'
    implementation 'com.palantir.safe-logging:preconditions'

    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
